CREATE TABLE Customer_details(
c_EmailID varchar(20),
c_Name varchar(20) not null,
mileage numeric(4,0),
registration_in_mlg_program char(1),
home_airport varchar(15),
miles_count numeric(6,0),
password varchar(15),
IATA_location_code char(6),
credit_card_no char(16),
card_type varchar(10) not null,
bank_Name varchar(15) not null,
expiry_Date date not null,
booking_ID varchar(10),
Address varchar(35),
Bonus_miles numeric(4,0),
airline_code char(6),
flight_no char(5),
Dep_airport varchar(15),
Dep_time time,
Arr_airport varchar(15),
Arr_time time,
Booking_type varchar(15),
Flight_date date,
booking_date date );

